### ISSUE TITLE
Any install instructions

### ISSUE THREAD

**Issue by billc** [gowalla-archive/chronologic#4]
I am interested in setting a service up, but the lack of a gem or install instructions is an obstacle. Do you have a blog post or any helpful information you use to get an environment up and running for those new to the Sinatra & Cassandra world.

**Comment by therealadam** [comment]
Quickstart, tutorial, and reference docs are all on my radar for a release.

FWIW, there will probably be a "we're using this version in production" release first, followed by a cleanup/documentation release.

**Comment by bulleric** [comment]
+1

**Comment by therealadam** [comment]
As it goes, I've posted a note about Chronologic's status:

http://weblog.therealadam.com/2012/06/17/chronologic-a-piece-of-software-history/

In short, it's not in use or developed anymore and so it's best use now is as something to read and learn from.
